### ISSUE TITLE
Spanish translations, and SMS flow for setting language preference

### ISSUE THREAD

**Issue by sethetter** [openwichita/voteict#15]
With #12 we have the foundations for i18n'd strings throughout the application, now we need to lock down the general messaging and get Spanish translations.

There's also a UX piece to think through -- how do we tell subscribers they can change their language preference, and then how do we do that?

Some options..

1. Tell the user after first subscribing that they can text "Spanish" or "English" to set their language preference. But then do we wait to send the "register to vote" link until after they've set their language? What if they never reply with a language preference? Default to English, probably, but then the register to vote link gets lost.

2. Allow people to text a "subscribe" keyword in their preferred language and use that to determine their preference. No extra SMS steps required this way. I think this might be the better way.

I'm sure there are other options I'm overlooking. Anyone have thoughts?

**Comment by imacrayon** [comment]
You could sent the “register to vote” message in all supported languages, prefixed with a number, and then then print them to pick their preferred language? This could be kind of spammy if there are a bunch of languages though

**Comment by imacrayon** [comment]
@sethetter I like two as well. So will the schedules messages need to be translated too? Would we use a service to do that or does there need to be both a “Spanish” and “English” field in the UI when creating a new scheduled message?

**Comment by sethetter** [comment]
@imacrayon what if the form shows a text area for each language, but there's a button to fetch a translation to populate the Spanish field with?

**Comment by sethetter** [comment]
Or if they leave it blank when creating, we can populate it using the translate service

**Comment by sethetter** [comment]
I think this is fixed by #22, and I added some translations in 6721af8. I'm going to open another ticket for letting scheduled messages be provided with a spanish translation,.
